services:
  totemexpress-db:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_DATABASE=totemexpress'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_USER=totemexpress'
    ports:
      - 3306:3306
    networks:
      - totemexpress
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 2s
      retries: 10

  totem-express:
    image: totem-express/webapp
    build: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://totemexpress-db:3306/totemexpress?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull&useSSL=false
      - SPRING_DATASOURCE_USERNAME=totemexpress
      - SPRING_DATASOURCE_PASSWORD=secret
    networks:
      - totemexpress
    ports:
      - 8080:8080
    depends_on:
      totemexpress-db:
        condition: service_healthy

networks:
  totemexpress:
