apiVersion: apps/v1
kind: Deployment
metadata:
  name: totem-express
  labels:
    app: totem-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: totem-express
  template:
    metadata:
      labels:
        app: totem-express
    spec              :
      containers:
        - name: totem-express
          image: DOCKER_IMAGE
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
          envFrom:
            - secretRef:
                name: totem-express-secret
            - configMapRef:
                name: totem-express-configmap
          resources:
            requests:
              cpu: 1000m
              memory: 1Gi
            limits:
              cpu: 1000m
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 2
            timeoutSeconds: 1
            failureThreshold: 10