apiVersion: v1
kind: Secret
metadata:
  name: totem-express-db-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: "dmVyeXNlY3JldA=="
  MYSQL_DATABASE: "dG90ZW1leHByZXNz"
  MYSQL_USER: "dG90ZW1leHByZXNz"
  MYSQL_PASSWORD: "c2VjcmV0"